### PR TITLE
Pyproject.toml

### LINKED ISSUE #11: Modernise the library structure to use `pyproject.toml`?
`ocf-data-sampler` was created from our template which I think is the slightly older way of doing it. We use `requirements.txt` and a `setup.py` file. We should check if the current best-practice is still to use `pyproject.toml` and update to whatever this best-practice is

### PR DESCRIPTION
**Pull request by peterdudfield**
# Pull Request

## Description

move to pyproject.toml

All work done in #48 Thanks @VikramsDataScience

Fixes #11 

## How Has This Been Tested?

CI tests

- [x] Yes

## Checklist:

- [ ] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by dfulu — APPROVED** [review]
Looks good! Thanks @VikramsDataScience

**Comment by VikramsDataScience** [comment]
My pleasure @dfulu!

**Comment by peterdudfield** [comment]
@all-contributors please add @VikramsDataScience for code.

**Comment by VikramsDataScience** [comment]
Thank you, @peterdudfield!

**Pull request merged**
