### PR TITLE
Refactor fill time periods function

### PR DESCRIPTION
**Pull request by Sukh-P**
# Pull Request

## Description
Small refactor of `fill_time_periods` to remove using `iterrows()` to hopefully make it more efficient 

## How Has This Been Tested?

A unit test already existed for this which is great so just checked that still passes

### CODE REVIEW

**Review by dfulu — CHANGES_REQUESTED** [review]
Could we use:

```
 start_dts = pd.to_datetime(time_periods["start_dt"]).ceil(freq)
 end_dts = pd.to_datetime(time_periods['end_dt'])
```
?

**Comment by Sukh-P** [comment]
> Could we use:
> 
> ```
>  start_dts = pd.to_datetime(time_periods["start_dt"]).ceil(freq)
>  end_dts = pd.to_datetime(time_periods['end_dt'])
> ```
> 
> ?

Yeah I thought of that and tried it but the tests failed, since they were strings in the test, but not sure if we always assume they are pd.Timestamps anyway and then we should change the test? If so then yeah removing that makes sense

**Comment by Sukh-P** [comment]
> Could we use:
> 
> ```
>  start_dts = pd.to_datetime(time_periods["start_dt"]).ceil(freq)
>  end_dts = pd.to_datetime(time_periods['end_dt'])
> ```
> 
> ?

So that won't work for the start_dts but yeah that's a nicer way to do the end_dts, will change that now

**Comment by dfulu** [comment]
> So that won't work for the start_dts but yeah that's a nicer way to do the end_dts, will change that now

Oh okay, why won't it work for the start_dts? I ran:

```
pd.to_datetime(["2020-01-01 11:22", "2020-01-01 11:55",]).ceil(pd.Timedelta("1h"))
>> DatetimeIndex(['2020-01-01 12:00:00', '2020-01-01 12:00:00'], dtype='datetime64[ns]', freq=None)
```

Am I missing something?

**Comment by Sukh-P** [comment]
I was missing a .values! Works now

**Comment by dfulu** [comment]
> I was missing a .values! Works now

Cool! Nice work. Sorry to nitpick but to keep it cleaner can we add `.values` to both, otherwise it raises the question of why only have it for one. Right now I think `start_dt` is a `pd.DatetimeIndex` but `end_dt` is a `pd.Series`

**Review by dfulu — APPROVED** [review]

**Pull request merged**
