### PR TITLE
Migration to pyproject.toml

### PR DESCRIPTION
**Pull request by VikramsDataScience**
# Pull Request

## Description (Attempt to migrate to pyproject to address `issue #11`)
- In line with the raised issue #11, this is my attempt to migrate the project to utilise `pyproject.toml`
- To support these changes, I've also deprecated the `setup.py` and `requirements.txt` file since the pyproject file has taken over those responsibilities.
- On this note, I'm not sure if the `python-test.yml` reusable workflow that is triggered by the `workflows.yaml` file would need to be modified to accommodate the new `pyproject.toml`? I say this because once I perform this push, it'll trigger this workflow, and the workflow might fail without this modification? That is to say, the section:
```
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-xdist
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f "setup.py" ]; then pip install -e .; else export PYTHONPATH=$PYTHONPATH:./src; fi
          echo "PYTHONPATH=$PYTHONPATH" >> $GITHUB_ENV
```

to be modified to also include the following?:
`	if [ -f pyproject.toml ]; then pip install -e .[docs]; fi`
I'm not sure about this part, though, as I'm still becoming familiar with your codebase! So please advise!
- I've also modified the `.readthedocs.yml` file to include the CLI command necessary to trigger `pyproject.toml`.

## How Has This Been Tested?
- To test my changes I created a virtual environment on my Windows machine
	- Create Virtual Environment:
	python -m venv venv
	- Activate Virtual Environment:
	venv/Scripts/activate
- Run `pip install -e .[docs]` in the `ocf-data-sampler` folder to run the new `pyproject.toml` file
- The full pyproject file took about 5 mins to run on my machine. It's a bit slow, so I'm not sure if that's a problem?

- [x] Yes

My changes shouldn't affect data processing but ticking the below box.
- [x] Yes

## Checklist:

- [x] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works (added instructions to test my code, but haven't written any unit tests)
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by peterdudfield** [comment]
Thanks @VikramsDataScience for doing this. 

Do you mind adjusting https://github.com/openclimatefix/ocf-data-sampler/blob/main/.bumpversion.cfg this too? 

Would you mind making a PR to the python-test.yml as your suggsted. 

Thanks again

**Comment by VikramsDataScience** [comment]
Hey @peterdudfield! I've made the changes to the `bumpversion.cfg`, tested the file and attached a screenshot of the test, and pushed the new commit:
image

I've also created a new PR for the change to the `python-test.yml` file under `gh pr checkout 54`. Please let me know if any other changes/bugs need to addressed :).

**Review by peterdudfield — APPROVED** [review]
Thank you very much for this. I might merge it to a dev branch to check ci works all ok. 

Thanks again

**Comment by VikramsDataScience** [comment]
Thank you, @peterdudfield! Please let me know if there are any issues, and I'll do my best to repair them 🙂!

In the meantime I'll poke through some of the other issues raised and attempt to further contribute!

**Comment by peterdudfield** [comment]
sorry @VikramsDataScience do you mind resolving the conflicts?

**Comment by VikramsDataScience** [comment]
Hey @peterdudfield. Done

**Comment by peterdudfield** [comment]
Can you see what went wrong here - https://github.com/openclimatefix/ocf-data-sampler/actions/runs/10936228269

**Comment by peterdudfield** [comment]
oh, it might be we need to delete setup.py

**Comment by VikramsDataScience** [comment]
I think you're right. I think it may also be looking for the requirements.txt, as well?:
image

Which is a little strange. Because the `pyproject.toml` should take care of that responsibility now. And the change we made to the `python-test.yml` file should only run the `if [ -f pyproject.toml ]; then pip install -e .[docs]; fi`?

**Comment by peterdudfield** [comment]
yea all good, i removed setup.py and it now works

Thank you for doing this

**Comment by VikramsDataScience** [comment]
No problems. It's my pleasure @peterdudfield! I'll work on the fake-data issue over the next few days, as well :).

**Pull request merged**
